name: avisa_la
description: "Alarme de destino para viagens de ônibus."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # App dependencies
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2
  audioplayers: ^6.0.0
  permission_handler: ^11.3.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
